version: '3.8'

services:
  knowledge-base:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./documents:/app/documents
      - ./faiss_index:/app/faiss_index
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-BAAI/bge-base-zh}
      - MODEL_NAME=${MODEL_NAME:-deepseek-chat}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - knowledge-base
    restart: unless-stopped

volumes:
  ollama_data:
