# Zeabur 配置文件 - Docker 部署
# 企業知識庫系統（前後端整合）

[build]
# 指定構建類型為 Docker
type = "docker"

# Docker 配置
dockerfile = "Dockerfile"

# 構建上下文
context = "."

# 構建參數
[build.args]
NODE_ENV = "production"
PYTHON_ENV = "production"

[run]
# 容器端口映射
port = 80

# 健康檢查端點
health_check = "/api/health"

# 啟動超時（秒）
start_timeout = 300

# 重啟策略
restart_policy = "always"

# 環境變數
[env]
# 生產環境設置
NODE_ENV = "production"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# 應用設置
PORT = "80"
HOST = "0.0.0.0"

# API 配置
EMBEDDING_MODEL = "BAAI/bge-base-zh"
MODEL_NAME = "deepseek-chat"

# 前端配置
NEXT_PUBLIC_API_URL = "/api"

# 資源限制
[resources]
# 記憶體限制（MB）
memory = 2048

# CPU 限制
cpu = 2.0

# 磁盤空間（GB）
disk = 10

# 服務配置
[services.app]
# 服務名稱
name = "intraknow-fullstack"

# 服務描述
description = "IntraKnow 企業知識庫系統 - 前後端整合版"

# 版本
version = "2.0.0"

# 區域偏好（選擇亞洲地區以獲得更好的性能）
regions = ["hkg", "nrt", "sin", "syd"]

# 自動擴展設置
[services.app.scaling]
min_instances = 1
max_instances = 2
target_cpu = 70
target_memory = 80

# 持久化存儲配置
[volumes]
# 用戶文檔存儲
user_documents = {
    mount_path = "/app/user_documents",
    size = "5GB"
}

# 用戶索引存儲
user_indexes = {
    mount_path = "/app/user_indexes", 
    size = "2GB"
}

# 數據庫存儲
database = {
    mount_path = "/app/knowledge_base.db",
    size = "1GB"
}

# 日誌存儲
logs = {
    mount_path = "/app/logs",
    size = "1GB"
}

# 網絡配置
[network]
# 自定義域名（可選）
# domains = ["your-domain.com"]

# HTTPS 設置
https = true

# 監控和日誌
[monitoring]
# 啟用監控
enabled = true

# 日誌級別
log_level = "info"

# 性能監控
metrics = true

# 錯誤追蹤
error_tracking = true

# 備份配置
[backup]
# 啟用自動備份
enabled = true

# 備份頻率（天）
frequency = 7

# 保留備份數量
retention = 4

# 通知設置
[notifications]
# 部署通知
deploy = true

# 錯誤通知
errors = true

# 性能警告
performance = true 