name: 部署到 Zeabur

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3
        
      - name: 設置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 安裝依賴
        run: npm ci
      
      - name: 建立應用
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      
      - name: 部署到 Zeabur
        uses: zeabur/cli-action@v1
        with:
          zeabur-token: ${{ secrets.ZEABUR_TOKEN }}
          workdir: '.'
          project: ${{ secrets.ZEABUR_PROJECT }}
          service: web
      
      - name: 部署API到 Zeabur
        uses: zeabur/cli-action@v1
        with:
          zeabur-token: ${{ secrets.ZEABUR_TOKEN }}
          workdir: './scripts'
          project: ${{ secrets.ZEABUR_PROJECT }}
          service: api
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }} 